language: cpp
compiler:
  - clang
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/julianightlies -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e 'versioninfo(); Pkg.init();'
  - julia -e 'map(x -> Pkg.add(strip(x)), readlines(open("REQUIRE")));'
  - mkdir -p ~/.julia/MachineLearning
  - cp -R ./* ~/.julia/MachineLearning/
  - julia ./run_tests.jl